# Ensures package builds correctly
name: Build Package

on:
  push:

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup NodeJS
        uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install sha3sum
        run: |
          sudo apt-get update
          sudo apt-get install -y libdigest-sha3-perl

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: "latest"
          actions-cache-folder: "emsdk-cache"

      - name: Build
        run: pnpm build
