# Ensures package builds correctly
name: Build Package

on:
  push:

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup NodeJS
        uses: actions/setup-node@v7
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install sha3sum
        run: |
          sudo apt-get update
          sudo apt-get install -y libdigest-sha3-perl

      - name: Setup Emscripten
        uses: emscripten-core/setup-emsdk@v16
        with:
          version: "latest"
          actions-cache-folder: "emsdk-cache"

      - name: Build
        run: pnpm build
