# Ensures package builds correctly
name: Build Package

on:
  push:

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
      
      - name: Update npm
        run: |
          npm install -g npm@latest
          npm --version

      - name: Install dependencies
        run: pnpm install

      - name: Install sha3sum
        run: |
          sudo apt-get update
          sudo apt-get install -y libdigest-sha3-perl

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: "latest"
          actions-cache-folder: "emsdk-cache"

      - name: Build
        run: pnpm build
