name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # Dev publishing

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write  # Required for OIDC
  contents: write # Required for changesets pushing
  pull-requests: write # Required for changesets to create PRs

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
      - name: Update npm
        run: |
          npm install -g npm@latest
          npm --version

      - name: Install dependencies
        run: pnpm install

      - name: Install sha3sum
        run: |
          sudo apt-get update
          sudo apt-get install -y libdigest-sha3-perl

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.10
          actions-cache-folder: "emsdk-cache"

      - name: Build
        run: pnpm build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        if: ${{ github.event_name == 'push' }}
        with:
          # Update the monorepo lockfile after versioning
          version: pnpm changeset:version
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dev publish
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          pnpm changeset version --no-git-tag --snapshot dev
          pnpm changeset publish --tag dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
